In [1]:
# TO DO: Instalação da biblioteca do pyod. Excutada uma única vez.
#!pip install pyod

Collecting pyod
  Downloading pyod-2.0.3.tar.gz (169 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 169.6/169.6 kB 3.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: joblib in /usr/local/lib/python3.11/dist-packages (from pyod) (1.4.2)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.11/dist-packages (from pyod) (3.10.0)
Requirement already satisfied: numpy>=1.19 in /usr/local/lib/python3.11/dist-packages (from pyod) (1.26.4)
Requirement already satisfied: numba>=0.51 in /usr/local/lib/python3.11/dist-packages (from pyod) (0.60.0)
Requirement already satisfied: scipy>=1.5.1 in /usr/local/lib/python3.11/dist-packages (from pyod) (1.13.1)
Requirement already satisfied: scikit-learn>=0.22.0 in /usr/local/lib/python3.11/dist-packages (from pyod) (1.6.1)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.11/dist-packages (from numba>=0.51->pyod) (0.43.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn>=0.22.0->pyod) (3.5.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib->pyod) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.11/dist-packages (from matplotlib->pyod) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib->pyod) (4.55.7)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib->pyod) (1.4.8)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib->pyod) (24.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.11/dist-packages (from matplotlib->pyod) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib->pyod) (3.2.1)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.11/dist-packages (from matplotlib->pyod) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.7->matplotlib->pyod) (1.17.0)
Building wheels for collected packages: pyod
  Building wheel for pyod (setup.py) ... done
  Created wheel for pyod: filename=pyod-2.0.3-py3-none-any.whl size=200466 sha256=e19858629b86bf66e4dd4ba4bd9d8133894f9d5e32062a17cc5889ca41a87f83
  Stored in directory: /root/.cache/pip/wheels/2d/60/5b/f74eccd2c9c892a2c298202ca510f10995f9940647fcc2d97f
Successfully built pyod
Installing collected packages: pyod
Successfully installed pyod-2.0.3

In [1]:
# -- Bibliotecas de tratamento de dados --
import pandas as pd
import numpy as np

from sklearn.preprocessing import LabelEncoder

# -- Bibliotecas de Vizualização de dados --
import plotly.express as px
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

# -- Importação do método para detecção de anomalias --
from pyod.models.iforest import IForest

print(pd.__version__)
print(np.__version__)

2.2.3
2.1.3

In [2]:
hr = pd.read_csv('HR.csv')

In [3]:
# TO DO: oberter um sample dos dados.
hr.head()

,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,sales,salary
0,0.38,0.53,2,157,3,0,1,0,sales,low
1,0.80,0.86,5,262,6,0,1,0,sales,medium
2,0.11,0.88,7,272,4,0,1,0,sales,medium
3,0.72,0.87,5,223,5,0,1,0,sales,low
4,0.37,0.52,2,159,3,0,1,0,sales,low

In [4]:
hr.describe().T

,count,mean,std,min,25%,50%,75%,max
satisfaction_level,14999.0,0.612834,0.248631,0.09,0.44,0.64,0.82,1.0
last_evaluation,14999.0,0.716102,0.171169,0.36,0.56,0.72,0.87,1.0
number_project,14999.0,3.803054,1.232592,2.00,3.00,4.00,5.00,7.0
average_montly_hours,14999.0,201.050337,49.943099,96.00,156.00,200.00,245.00,310.0
time_spend_company,14999.0,3.498233,1.460136,2.00,3.00,3.00,4.00,10.0
Work_accident,14999.0,0.144610,0.351719,0.00,0.00,0.00,0.00,1.0
left,14999.0,0.238083,0.425924,0.00,0.00,0.00,0.00,1.0
promotion_last_5years,14999.0,0.021268,0.144281,0.00,0.00,0.00,0.00,1.0

In [5]:
#Verificando valores ausentes
print(hr.isnull().sum())

satisfaction_level       0
last_evaluation          0
number_project           0
average_montly_hours     0
time_spend_company       0
Work_accident            0
left                     0
promotion_last_5years    0
sales                    0
salary                   0
dtype: int64

In [6]:
hr.shape

(14999, 10)

In [8]:
hr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14999 entries, 0 to 14998
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   satisfaction_level     14999 non-null  float64
 1   last_evaluation        14999 non-null  float64
 2   number_project         14999 non-null  int64
 3   average_montly_hours   14999 non-null  int64
 4   time_spend_company     14999 non-null  int64
 5   Work_accident          14999 non-null  int64
 6   left                   14999 non-null  int64
 7   promotion_last_5years  14999 non-null  int64
 8   sales                  14999 non-null  object
 9   salary                 14999 non-null  object
dtypes: float64(2), int64(6), object(2)
memory usage: 1.1+ MB

In [9]:
# TO DO: Deixar todos os nomes de colunas em maiúsculas.
hr.columns = hr.columns.str.upper()
hr.columns

Index(['SATISFACTION_LEVEL', 'LAST_EVALUATION', 'NUMBER_PROJECT',
       'AVERAGE_MONTLY_HOURS', 'TIME_SPEND_COMPANY', 'WORK_ACCIDENT', 'LEFT',
       'PROMOTION_LAST_5YEARS', 'SALES', 'SALARY'],
      dtype='object')

## Aplicando Label Enconding


Fonte: https://towardsdatascience.com/categorical-encoding-using-label-encoding-and-one-hot-encoder-911ef77fb5bd

In [10]:
# CRIANDO UMA INSTÂNCIA DA CLASSE LabelEncoder do sci-kit learn
labelencoder = LabelEncoder()

# Assigning numerical values and storing in another column
hr['SALES'] = labelencoder.fit_transform(hr['SALES'])

In [11]:
# CRIANDO UMA INSTÂNCIA DA CLASSE LabelEncoder do sci-kit learn
labelencoder = LabelEncoder()

# Assigning numerical values and storing in another column
hr['SALARY'] = labelencoder.fit_transform(hr['SALARY'])

In [12]:
hr.head()

,SATISFACTION_LEVEL,LAST_EVALUATION,NUMBER_PROJECT,AVERAGE_MONTLY_HOURS,TIME_SPEND_COMPANY,WORK_ACCIDENT,LEFT,PROMOTION_LAST_5YEARS,SALES,SALARY
0,0.38,0.53,2,157,3,0,1,0,7,1
1,0.80,0.86,5,262,6,0,1,0,7,2
2,0.11,0.88,7,272,4,0,1,0,7,2
3,0.72,0.87,5,223,5,0,1,0,7,1
4,0.37,0.52,2,159,3,0,1,0,7,1

In [13]:
# hr.LEFT = hr.LEFT.astype('category')
# hr.info()

## Detecção de Outliers de forma visual

In [20]:
# Schema de cores possíveis
# ['Alphabet',
#  'Antique',
#  'Bold',
#  'D3',
#  'Dark2',
#  'Dark24',
#  'G10',

fig = px.scatter(hr,
                 x='LAST_EVALUATION',
                 y='AVERAGE_MONTLY_HOURS',
                 color='LEFT',
                 color_discrete_sequence=px.colors.qualitative.Antique
                 )

fig.show()

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

In [ ]:
# TO DO: Utilizar um boxplot para verificação de outliers.

## Aplicação do modelo IsolationForeset para Deteção de Anomalias

In [23]:
#TO DO: Aplicação do algoritmo para detecção de anomalias
import plotly.express as px
fig = px.box(hr,
             y = 'SATISFACTION_LEVEL')
fig.show()

In [26]:
# classificação de quem é outliers ou não
outliner_detection_clf = IForest(contamination=0.05, #Porcentagem de outliers que desejamos encontrar na amostra
                             random_state = 42,
                             verbose=True)

outliner_detection_clf.fit(hr)

y_pred = outliner_detection_clf.predict(hr)

# Contando os outliers
n_outliers = np.count_nonzero(y_pred ==1)

print(f'\nExistem {n_outliers} outliners dentro dessa amostra\n')
#print("número de outliders:", n_outliers)

[Parallel(n_jobs=1)]: Done  49 tasks      | elapsed:    0.0s
[Parallel(n_jobs=1)]: Done  49 tasks      | elapsed:    0.0s
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2732: UserWarning:

X has feature names, but IsolationForest was fitted without feature names

[Parallel(n_jobs=1)]: Done  49 tasks      | elapsed:    0.0s

Existem 750 outliners dentro dessa amostra

In [37]:
# TO DO:  Mostrar a quantidade de outliers e não outliers
#np.unique(y_pred, return_counts=True)

out = hr.loc[hr['OUTLIERS'] == 1]
print(f'Quantidade de outliers: {(len(out))}')

Quantidade de outliers: 750

In [34]:
y_pred

array([0, 0, 0, ..., 0, 0, 0])

In [38]:
# TO DO: Criando uma nova coluna para classificação dos outliers (0 = inliders, 1 = outliers).
hr['OUTLIERS'] = y_pred.tolist()

In [39]:
hr.head()

,SATISFACTION_LEVEL,LAST_EVALUATION,NUMBER_PROJECT,AVERAGE_MONTLY_HOURS,TIME_SPEND_COMPANY,WORK_ACCIDENT,LEFT,PROMOTION_LAST_5YEARS,SALES,SALARY,OUTLIERS
0,0.38,0.53,2,157,3,0,1,0,7,1,0
1,0.80,0.86,5,262,6,0,1,0,7,2,0
2,0.11,0.88,7,272,4,0,1,0,7,2,0
3,0.72,0.87,5,223,5,0,1,0,7,1,0
4,0.37,0.52,2,159,3,0,1,0,7,1,0

In [47]:
# TO DO: Apresentando somente os X% de outliers identificados no conjunto de dados.
out = hr.loc[hr['OUTLIERS'] == 1] #Contando a quantidade de outliers
p_outliers = (out / len(hr['OUTLIERS']))*100
print(f'\ Porcentagem de outliers {p_outliers} da amostra\n')

\ Porcentagem de outliers        SATISFACTION_LEVEL  LAST_EVALUATION  NUMBER_PROJECT  \
18               0.003000         0.003400        0.013334
30               0.000600         0.004134        0.040003
61               0.000733         0.006200        0.046670
62               0.000667         0.006334        0.040003
65               0.005400         0.004667        0.040003
...                   ...              ...             ...
14940            0.000667         0.005200        0.033336
14942            0.001333         0.003334        0.033336
14945            0.000933         0.005000        0.026668
14946            0.000667         0.005600        0.033336
14975            0.000667         0.005267        0.046670

       AVERAGE_MONTLY_HOURS  TIME_SPEND_COMPANY  WORK_ACCIDENT      LEFT  \
18                 1.066738            0.020001       0.006667  0.006667
30                 1.960131            0.026668       0.000000  0.006667
61                 2.053470            0.026668       0.000000  0.006667
62                 1.626775            0.033336       0.000000  0.006667
65                 1.073405            0.026668       0.000000  0.006667
...                     ...                 ...            ...       ...
14940              1.900127            0.026668       0.006667  0.006667
14942              0.900060            0.040003       0.000000  0.006667
14945              1.846790            0.033336       0.006667  0.006667
14946              2.020135            0.033336       0.000000  0.006667
14975              2.066804            0.026668       0.000000  0.006667

       PROMOTION_LAST_5YEARS     SALES    SALARY  OUTLIERS
18                  0.006667  0.046670  0.006667  0.006667
30                  0.000000  0.013334  0.006667  0.006667
61                  0.000000  0.000000  0.013334  0.006667
62                  0.000000  0.000000  0.013334  0.006667
65                  0.000000  0.000000  0.013334  0.006667
...                      ...       ...       ...       ...
14940               0.000000  0.006667  0.013334  0.006667
14942               0.000000  0.006667  0.006667  0.006667
14945               0.000000  0.046670  0.013334  0.006667
14946               0.000000  0.013334  0.013334  0.006667
14975               0.000000  0.020001  0.013334  0.006667

[750 rows x 11 columns] da amostra