In [ ]:
import pandas as pd
pd.set_option('display.max_columns', None)

In [ ]:
ocorrencia = pd.read_csv('/content/ocorrencia.csv', encoding="ISO-8859-1", sep=';')

In [ ]:
ocorrencia.tail()

,codigo_ocorrencia,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,ocorrencia_pais,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
13180,28377,28377,28377,28377,28377,ACIDENTE,***,***,IMPERATRIZ,MA,BRASIL,FAER,27/01/2007,11:18:00,SIM,FINALIZADA,A-053/CENIPA/2009,SIM,2009-11-16,2,1,NÃO
13181,28375,28375,28375,28375,28375,ACIDENTE,-23.6122222222,-51.385,APUCARANA,PR,BRASIL,FAER,26/01/2007,18:15:00,SIM,FINALIZADA,A-021/CENIPA/2010,SIM,2007-08-15,1,1,NÃO
13182,28355,28355,28355,28355,28355,ACIDENTE,-17.2541666667,-43.8536111111,BOCAIÚVA,MG,BRASIL,FAER,18/01/2007,09:10:00,SIM,FINALIZADA,A-001/CENIPA/2010,SIM,2010-03-19,11,1,NÃO
13183,28335,28335,28335,28335,28335,ACIDENTE,-23.3444444444,-51.0633333333,LONDRINA,PR,BRASIL,FAER,19/01/2007,12:30:00,SIM,FINALIZADA,A-169/CENIPA/2013,SIM,2013-12-16,1,1,NÃO
13184,28256,28256,28256,28256,28256,ACIDENTE,-22.2180555556,-47.1763888889,MOGI GUAÇU,SP,BRASIL,FAER,07/01/2007,11:30:00,SIM,FINALIZADA,A-112/CENIPA/2012,SIM,2012-10-17,2,1,NÃO

from matplotlib import pyplot as plt
_df_0['codigo_ocorrencia'].plot(kind='hist', bins=20, title='codigo_ocorrencia')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_1['codigo_ocorrencia1'].plot(kind='hist', bins=20, title='codigo_ocorrencia1')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_2['codigo_ocorrencia2'].plot(kind='hist', bins=20, title='codigo_ocorrencia2')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_3['codigo_ocorrencia3'].plot(kind='hist', bins=20, title='codigo_ocorrencia3')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_4.groupby('ocorrencia_latitude').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_5.groupby('ocorrencia_longitude').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_6.groupby('ocorrencia_cidade').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_7.groupby('ocorrencia_uf').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_8.plot(kind='scatter', x='codigo_ocorrencia', y='codigo_ocorrencia1', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_9.plot(kind='scatter', x='codigo_ocorrencia1', y='codigo_ocorrencia2', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_10.plot(kind='scatter', x='codigo_ocorrencia2', y='codigo_ocorrencia3', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_11.plot(kind='scatter', x='codigo_ocorrencia3', y='codigo_ocorrencia4', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['total_aeronaves_envolvidas']
  ys = series['codigo_ocorrencia']

  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_12.sort_values('total_aeronaves_envolvidas', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('ocorrencia_latitude')):
  _plot_series(series, series_name, i)
  fig.legend(title='ocorrencia_latitude', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('total_aeronaves_envolvidas')
_ = plt.ylabel('codigo_ocorrencia')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['total_aeronaves_envolvidas']
  ys = series['codigo_ocorrencia']

  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_13.sort_values('total_aeronaves_envolvidas', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('ocorrencia_longitude')):
  _plot_series(series, series_name, i)
  fig.legend(title='ocorrencia_longitude', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('total_aeronaves_envolvidas')
_ = plt.ylabel('codigo_ocorrencia')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['total_aeronaves_envolvidas']
  ys = series['codigo_ocorrencia']

  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_14.sort_values('total_aeronaves_envolvidas', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('ocorrencia_cidade')):
  _plot_series(series, series_name, i)
  fig.legend(title='ocorrencia_cidade', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('total_aeronaves_envolvidas')
_ = plt.ylabel('codigo_ocorrencia')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['total_aeronaves_envolvidas']
  ys = series['codigo_ocorrencia']

  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_15.sort_values('total_aeronaves_envolvidas', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('ocorrencia_uf')):
  _plot_series(series, series_name, i)
  fig.legend(title='ocorrencia_uf', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('total_aeronaves_envolvidas')
_ = plt.ylabel('codigo_ocorrencia')

from matplotlib import pyplot as plt
_df_16['codigo_ocorrencia'].plot(kind='line', figsize=(8, 4), title='codigo_ocorrencia')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_17['codigo_ocorrencia1'].plot(kind='line', figsize=(8, 4), title='codigo_ocorrencia1')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_18['codigo_ocorrencia2'].plot(kind='line', figsize=(8, 4), title='codigo_ocorrencia2')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_19['codigo_ocorrencia3'].plot(kind='line', figsize=(8, 4), title='codigo_ocorrencia3')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['ocorrencia_longitude'].value_counts()
    for x_label, grp in _df_20.groupby('ocorrencia_latitude')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('ocorrencia_latitude')
_ = plt.ylabel('ocorrencia_longitude')

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['ocorrencia_cidade'].value_counts()
    for x_label, grp in _df_21.groupby('ocorrencia_longitude')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('ocorrencia_longitude')
_ = plt.ylabel('ocorrencia_cidade')

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['ocorrencia_uf'].value_counts()
    for x_label, grp in _df_22.groupby('ocorrencia_cidade')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('ocorrencia_cidade')
_ = plt.ylabel('ocorrencia_uf')

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['ocorrencia_dia'].value_counts()
    for x_label, grp in _df_23.groupby('ocorrencia_uf')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('ocorrencia_uf')
_ = plt.ylabel('ocorrencia_dia')

<string>:5: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_24['ocorrencia_latitude'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_24, x='codigo_ocorrencia', y='ocorrencia_latitude', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_25['ocorrencia_longitude'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_25, x='codigo_ocorrencia', y='ocorrencia_longitude', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_26['ocorrencia_cidade'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_26, x='codigo_ocorrencia', y='ocorrencia_cidade', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_27['ocorrencia_uf'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_27, x='codigo_ocorrencia', y='ocorrencia_uf', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

In [ ]:
ocorrencia['total_aeronaves_envolvidas'].describe()

count    13185.000000
mean         1.008722
std          0.098532
min          0.000000
25%          1.000000
50%          1.000000
75%          1.000000
max          4.000000
Name: total_aeronaves_envolvidas, dtype: float64

In [ ]:
ocorrencia.count().isnull()

codigo_ocorrencia                 False
codigo_ocorrencia1                False
codigo_ocorrencia2                False
codigo_ocorrencia3                False
codigo_ocorrencia4                False
ocorrencia_classificacao          False
ocorrencia_latitude               False
ocorrencia_longitude              False
ocorrencia_cidade                 False
ocorrencia_uf                     False
ocorrencia_pais                   False
ocorrencia_aerodromo              False
ocorrencia_dia                    False
ocorrencia_hora                   False
investigacao_aeronave_liberada    False
investigacao_status               False
divulgacao_relatorio_numero       False
divulgacao_relatorio_publicado    False
divulgacao_dia_publicacao         False
total_recomendacoes               False
total_aeronaves_envolvidas        False
ocorrencia_saida_pista            False
dtype: bool

In [ ]:
ocorrencia[['ocorrencia_aerodromo','ocorrencia_cidade', 'ocorrencia_uf']].value_counts()

ocorrencia_aerodromo  ocorrencia_cidade  ocorrencia_uf
SBGR                  GUARULHOS          SP               627
SBGL                  RIO DE JANEIRO     RJ               397
SBKP                  CAMPINAS           SP               374
SBSP                  SÃO PAULO          SP               319
SBBR                  BRASÍLIA           DF               316
                                                         ...
FAER                  UNIÃO              PI                 1
                      UNIÃO DA VITÓRIA   PR                 1
                      UNIÃO DE MINAS     MG                 1
                      URANDI             BA                 1
                      TUMIRITINGA        MG                 1
Name: count, Length: 2339, dtype: int64

In [ ]:
#ocorrencia.drop(columns=['codigo_ocorrencia1','codigo_ocorrencia2','codigo_ocorrencia3','codigo_ocorrencia4'])
ocorrencia_drop = ocorrencia.drop(columns=['codigo_ocorrencia1','codigo_ocorrencia2','codigo_ocorrencia3','codigo_ocorrencia4'])
ocorrencia_drop.head(20)

,codigo_ocorrencia,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,ocorrencia_pais,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
0,87125,INCIDENTE,-7.219166666666,-39.26944444444,JUAZEIRO DO NORTE,CE,BRASIL,FAER,11/05/2025,04:20:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
1,87124,INCIDENTE,-18.88361111111,-48.22527777777,UBERLÂNDIA,MG,BRASIL,SBUL,08/05/2025,14:00:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
2,87123,INCIDENTE,-23.43555555555,-46.47305555555,GUARULHOS,SP,BRASIL,SBGR,09/05/2025,18:45:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
3,87122,INCIDENTE,-29.71083333333,-53.69222222222,SANTA MARIA,RS,BRASIL,SBSM,04/05/2025,14:45:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
4,87121,INCIDENTE,-20.81722222222,-49.40694444444,SÃO JOSÉ DO RIO PRETO,SP,BRASIL,SBSR,10/05/2025,10:00:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
5,87118,INCIDENTE,-15.87111111111,-47.91861111111,BRASÍLIA,DF,BRASIL,SBBR,07/05/2025,11:15:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
6,87117,INCIDENTE,-3.775833333333,-38.53222222222,FORTALEZA,CE,BRASIL,FAER,19/04/2025,15:45:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
7,87116,INCIDENTE,NaN,NaN,GUARULHOS,SP,BRASIL,FAER,05/05/2025,16:45:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
8,87115,INCIDENTE,-9.510833333333,-35.79166666666,MACEIÓ,AL,BRASIL,SBMO,25/04/2025,15:30:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
9,87114,INCIDENTE,-16.6325,-49.22111111111,GOIÂNIA,GO,BRASIL,SBGO,04/05/2025,18:30:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
10,87113,INCIDENTE,-22.9875,-43.37,RIO DE JANEIRO,RJ,BRASIL,SBJR,18/04/2025,16:00:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
11,87112,INCIDENTE,-22.9875,-43.37,RIO DE JANEIRO,RJ,BRASIL,FAER,05/05/2025,23:45:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
12,87111,ACIDENTE,-6.304444444444,-50.91333333333,PARAUAPEBAS,PA,BRASIL,NCAD,05/05/2025,20:30:00,NÃO,ATIVA,A DEFINIR,NÃO,NaN,0,1,NÃO
13,87110,INCIDENTE,-2.586944444444,-44.23611111111,SÃO LUÍS,MA,BRASIL,SBSL,05/05/2025,19:55:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
14,87109,INCIDENTE,-13.78222222222,-58.91555555555,SAPEZAL,MT,BRASIL,FAER,05/04/2025,15:30:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
15,87108,INCIDENTE,-23.43555555555,-46.47305555555,GUARULHOS,SP,BRASIL,SBGR,25/03/2025,11:45:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
16,87107,INCIDENTE,-23.43555555555,-46.47305555555,GUARULHOS,SP,BRASIL,SBGR,29/03/2025,12:00:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
17,87106,INCIDENTE,-22.81,-43.25055555555,RIO DE JANEIRO,RJ,BRASIL,SBGL,05/05/2025,14:00:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
18,87105,INCIDENTE,-3.041111111111,-60.05055555555,MANAUS,AM,BRASIL,SBEG,02/05/2025,16:37:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
19,87104,INCIDENTE,-23.43555555555,-46.47305555555,GUARULHOS,SP,BRASIL,SBGR,27/04/2025,19:41:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO

In [ ]:
ocorrencia_drop.value_counts()

codigo_ocorrencia  ocorrencia_classificacao  ocorrencia_latitude  ocorrencia_longitude  ocorrencia_cidade      ocorrencia_uf  ocorrencia_pais  ocorrencia_aerodromo  ocorrencia_dia  ocorrencia_hora  investigacao_aeronave_liberada  investigacao_status  divulgacao_relatorio_numero  divulgacao_relatorio_publicado  divulgacao_dia_publicacao  total_recomendacoes  total_aeronaves_envolvidas  ocorrencia_saida_pista
85239              ACIDENTE                  -26.21277777777      -48.53611111111       SÃO FRANCISCO DO SUL   SC             BRASIL           SSSS                  28/07/2024      17:25:00         SIM                             FINALIZADA           A-111/CENIPA/2024            SIM                             2025-04-22                 0                    1                           NÃO                       1
28256              ACIDENTE                  -22.2180555556       -47.1763888889        MOGI GUAÇU             SP             BRASIL           FAER                  07/01/2007      11:30:00         SIM                             FINALIZADA           A-112/CENIPA/2012            SIM                             2012-10-17                 2                    1                           NÃO                       1
28335              ACIDENTE                  -23.3444444444       -51.0633333333        LONDRINA               PR             BRASIL           FAER                  19/01/2007      12:30:00         SIM                             FINALIZADA           A-169/CENIPA/2013            SIM                             2013-12-16                 1                    1                           NÃO                       1
81696              ACIDENTE                  -15.10305555555      -53.36305555555       NOVO SÃO JOAQUIM       MT             BRASIL           FAER                  03/06/2023      11:50:00         SIM                             FINALIZADA           A-095/CENIPA/2023            SIM                             2024-12-19                 0                    1                           NÃO                       1
81673              ACIDENTE                  -14.71305555555      -45.52416666666       COCOS                  BA             BRASIL           APUA                  23/05/2023      19:40:00         SIM                             ATIVA                A-088/CENIPA/2023            SIM                             2025-05-14                 1                    1                           NÃO                       1
                                                                                                                                                                                                                                                                                                                                                                                                                             ..
28437              ACIDENTE                  -29.3647222222       -50.8272222222        FERNANDO DE NORONHA    PE             BRASIL           FAER                  16/02/2007      20:45:00         SIM                             FINALIZADA           A-020/CENIPA/2014            SIM                             2014-06-02                 1                    1                           NÃO                       1
28395              ACIDENTE                  -14.8186111111       -55.9047222222        CHAPADA DOS GUIMARÃES  MT             BRASIL           FAER                  07/02/2007      10:10:00         SIM                             FINALIZADA           A-127/CENIPA/2011            SIM                             2011-12-21                 1                    1                           NÃO                       1
28379              ACIDENTE                  -11.0202777778       -45.1861111111        FORMOSA DO RIO PRETO   BA             BRASIL           FAER                  31/01/2007      09:40:00         SIM                             FINALIZADA           A-003/CENIPA/2012            SIM                             2012-02-22                 6                    1                           NÃO                       1
28377              ACIDENTE                  ***                  ***                   IMPERATRIZ             MA             BRASIL           FAER                  27/01/2007      11:18:00         SIM                             FINALIZADA           A-053/CENIPA/2009            SIM                             2009-11-16                 2                    1                           NÃO                       1
28375              ACIDENTE                  -23.6122222222       -51.385               APUCARANA              PR             BRASIL           FAER                  26/01/2007      18:15:00         SIM                             FINALIZADA           A-021/CENIPA/2010            SIM                             2007-08-15                 1                    1                           NÃO                       1
Name: count, Length: 2499, dtype: int64

In [ ]:
#ocorrencia_drop['ocorrencia_saida_pista'].value_counts()
ocorrencia_drop['total_aeronaves_envolvidas'].value_counts()

total_aeronaves_envolvidas
1    13073
2      107
3        3
0        1
4        1
Name: count, dtype: int64

In [ ]:
[['ocorrencia_classificacao',	'ocorrencia_cidade', 'ocorrencia_uf',	'ocorrencia_aerodromo',	'ocorrencia_dia',	'ocorrencia_hora', investigacao_aeronave_liberada	investigacao_status	divulgacao_relatorio_numero	divulgacao_relatorio_publicado	divulgacao_dia_publicacao	total_recomendacoes	total_aeronaves_envolvidas	ocorrencia_saida_pista